"""add_sales_crm_models

Revision ID: c93fcfd07a5d
Revises: 20260510_0020
Create Date: 2026-05-12 10:57:23.642076
"""
from alembic import op
import sqlalchemy as sa



revision = 'c93fcfd07a5d'
down_revision = '20260510_0020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_leads_status'), 'sales_leads', ['status'], unique=False)
    op.create_table('sales_lead_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_lead_notes_lead_id'), 'sales_lead_notes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_lead_notes_lead_id'), table_name='sales_lead_notes')
    op.drop_table('sales_lead_notes')
    op.drop_index(op.f('ix_sales_leads_status'), table_name='sales_leads')
    op.drop_table('sales_leads')
    # ### end Alembic commands ###

