"""fix_missing_embeddings_columns

Revision ID: 18c9b4380f1f
Revises: 9c33d5ddfc71
Create Date: 2026-05-09 15:17:57.338604
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "18c9b4380f1f"
down_revision = "9c33d5ddfc71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "billing_plans",
        sa.Column("embeddings_enabled", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.add_column(
        "billing_plans",
        sa.Column(
            "embeddings_requests_per_month", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "billing_plans",
        sa.Column("embeddings_tokens_per_month", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "billing_plans",
        sa.Column(
            "embeddings_max_inputs_per_request", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "quota_counters",
        sa.Column("used_embeddings_requests", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "quota_counters",
        sa.Column("used_embeddings_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column(
        "rag_document_chunks",
        "embedding",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "rag_document_chunks",
        "metadata_json",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.add_column(
        "usage_records",
        sa.Column("embeddings_requests", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "usage_records",
        sa.Column("embeddings_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "embeddings_tokens")
    op.drop_column("usage_records", "embeddings_requests")
    op.alter_column(
        "rag_document_chunks",
        "metadata_json",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "rag_document_chunks",
        "embedding",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("quota_counters", "used_embeddings_tokens")
    op.drop_column("quota_counters", "used_embeddings_requests")
    op.drop_column("billing_plans", "embeddings_max_inputs_per_request")
    op.drop_column("billing_plans", "embeddings_tokens_per_month")
    op.drop_column("billing_plans", "embeddings_requests_per_month")
    op.drop_column("billing_plans", "embeddings_enabled")
    # ### end Alembic commands ###
