"""Add collab chat tables

Revision ID: 25429dd20685
Revises: c106a65929ce
Create Date: 2026-06-01 20:43:51.475218
"""

import sqlalchemy as sa
from alembic import op

revision = "25429dd20685"
down_revision = "c106a65929ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_channels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_channels_tenant_id"), "chat_channels", ["tenant_id"], unique=False
    )
    op.create_table(
        "chat_presence_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_presence_events_user_id"), "chat_presence_events", ["user_id"], unique=False
    )
    op.create_table(
        "chat_channel_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["chat_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_channel_members_channel_id"),
        "chat_channel_members",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_channel_members_user_id"), "chat_channel_members", ["user_id"], unique=False
    )
    op.create_table(
        "chat_agent_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("auto_reply", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agent_definitions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["channel_id"], ["chat_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_agent_participants_agent_id"),
        "chat_agent_participants",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_agent_participants_channel_id"),
        "chat_agent_participants",
        ["channel_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_type", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agent_definitions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["channel_id"], ["chat_channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_agent_id"), "chat_messages", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_channel_id"), "chat_messages", ["channel_id"], unique=False
    )
    op.create_index(op.f("ix_chat_messages_user_id"), "chat_messages", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_user_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_channel_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_agent_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(
        op.f("ix_chat_agent_participants_channel_id"), table_name="chat_agent_participants"
    )
    op.drop_index(op.f("ix_chat_agent_participants_agent_id"), table_name="chat_agent_participants")
    op.drop_table("chat_agent_participants")
    op.drop_index(op.f("ix_chat_channel_members_user_id"), table_name="chat_channel_members")
    op.drop_index(op.f("ix_chat_channel_members_channel_id"), table_name="chat_channel_members")
    op.drop_table("chat_channel_members")
    op.drop_index(op.f("ix_chat_presence_events_user_id"), table_name="chat_presence_events")
    op.drop_table("chat_presence_events")
    op.drop_index(op.f("ix_chat_channels_tenant_id"), table_name="chat_channels")
    op.drop_table("chat_channels")
    # ### end Alembic commands ###
