"""Add request_financials fixed

Revision ID: 6aa96c5bcb12
Revises: 20260513_0028
Create Date: 2026-05-13 19:55:16.335487
"""

import sqlalchemy as sa
from alembic import op

revision = "6aa96c5bcb12"
down_revision = "20260513_0028"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abuse_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("api_key_prefix", sa.String(length=16), nullable=True),
        sa.Column("signal", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("detail_json", sa.Text(), nullable=True),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("endpoint", sa.String(length=128), nullable=True),
        sa.Column("estimated_cost_brl", sa.Float(), nullable=True),
        sa.Column("action_taken", sa.String(length=32), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abuse_events_api_key_prefix"), "abuse_events", ["api_key_prefix"], unique=False
    )
    op.create_index(op.f("ix_abuse_events_client_id"), "abuse_events", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_abuse_events_correlation_id"), "abuse_events", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_abuse_events_signal"), "abuse_events", ["signal"], unique=False)
    op.create_index(op.f("ix_abuse_events_source_ip"), "abuse_events", ["source_ip"], unique=False)
    op.create_table(
        "cache_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("billing_plan_code", sa.String(length=32), nullable=True),
        sa.Column("cache_enabled", sa.Boolean(), nullable=False),
        sa.Column("semantic_cache_enabled", sa.Boolean(), nullable=False),
        sa.Column("cache_ttl_seconds", sa.Integer(), nullable=False),
        sa.Column("cache_sensitive_data_allowed", sa.Boolean(), nullable=False),
        sa.Column("cache_price_discount_percent", sa.Float(), nullable=False),
        sa.Column("max_cache_entries", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cache_policies_billing_plan_code"),
        "cache_policies",
        ["billing_plan_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cache_policies_client_id"), "cache_policies", ["client_id"], unique=True
    )
    op.create_table(
        "request_financials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("request_log_id", sa.UUID(), nullable=True),
        sa.Column("api_key_prefix", sa.String(length=12), nullable=True),
        sa.Column("endpoint_type", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("requested_model", sa.String(length=255), nullable=True),
        sa.Column("resolved_model", sa.String(length=255), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("provider_cost_usd", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("provider_cost_brl", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("customer_price_brl", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("gross_profit_brl", sa.Numeric(precision=14, scale=8), nullable=True),
        sa.Column("margin_percent", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("fx_rate", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("fx_rate_source", sa.String(length=32), nullable=True),
        sa.Column("pricing_rule_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_request_financials_client_id"), "request_financials", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_request_financials_request_log_id"),
        "request_financials",
        ["request_log_id"],
        unique=False,
    )
    op.create_table(
        "abuse_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("abuse_event_id", sa.UUID(), nullable=True),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("detail_json", sa.Text(), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=64), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("auto_suspend", sa.Boolean(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["abuse_event_id"],
            ["abuse_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_abuse_actions_abuse_event_id"), "abuse_actions", ["abuse_event_id"], unique=False
    )
    op.create_index(
        op.f("ix_abuse_actions_client_id"), "abuse_actions", ["client_id"], unique=False
    )
    op.drop_constraint("ai_wallets_client_id_key", "ai_wallets", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("ai_wallets_client_id_key", "ai_wallets", ["client_id"])
    op.drop_index(op.f("ix_abuse_actions_client_id"), table_name="abuse_actions")
    op.drop_index(op.f("ix_abuse_actions_abuse_event_id"), table_name="abuse_actions")
    op.drop_table("abuse_actions")
    op.drop_index(op.f("ix_request_financials_request_log_id"), table_name="request_financials")
    op.drop_index(op.f("ix_request_financials_client_id"), table_name="request_financials")
    op.drop_table("request_financials")
    op.drop_index(op.f("ix_cache_policies_client_id"), table_name="cache_policies")
    op.drop_index(op.f("ix_cache_policies_billing_plan_code"), table_name="cache_policies")
    op.drop_table("cache_policies")
    op.drop_index(op.f("ix_abuse_events_source_ip"), table_name="abuse_events")
    op.drop_index(op.f("ix_abuse_events_signal"), table_name="abuse_events")
    op.drop_index(op.f("ix_abuse_events_correlation_id"), table_name="abuse_events")
    op.drop_index(op.f("ix_abuse_events_client_id"), table_name="abuse_events")
    op.drop_index(op.f("ix_abuse_events_api_key_prefix"), table_name="abuse_events")
    op.drop_table("abuse_events")
    # ### end Alembic commands ###
