"""phase65_runtime_fabric

Revision ID: 76dbcad4cbd8
Revises: phase63_control_plane_mesh
Create Date: 2026-05-15 16:16:07.490602
"""
import sqlalchemy as sa
from alembic import op

revision = '76dbcad4cbd8'
down_revision = 'phase63_control_plane_mesh'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_runtime_fabric_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('source_node_id', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_runtime_fabric_events_event_type'), 'commercial_runtime_fabric_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_commercial_runtime_fabric_events_source_node_id'), 'commercial_runtime_fabric_events', ['source_node_id'], unique=False)

    op.create_table('commercial_runtime_fabric_health',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('quarum_status', sa.Boolean(), nullable=True),
    sa.Column('degraded_mode_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_runtime_fabric_health_node_id'), 'commercial_runtime_fabric_health', ['node_id'], unique=False)

    op.create_table('commercial_runtime_recovery_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('execution_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['commercial_runtime_fabric_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('commercial_runtime_determinism_drift',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('expected_hash', sa.String(), nullable=True),
    sa.Column('actual_hash', sa.String(), nullable=True),
    sa.Column('drift_details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('repaired_at', sa.DateTime(), nullable=True),
    sa.Column('repair_plan_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repair_plan_id'], ['commercial_runtime_recovery_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_runtime_determinism_drift_workflow_id'), 'commercial_runtime_determinism_drift', ['workflow_id'], unique=False)

    op.create_table('commercial_runtime_healing_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('signed_receipt', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['commercial_runtime_recovery_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commercial_runtime_healing_actions')
    op.drop_index(op.f('ix_commercial_runtime_determinism_drift_workflow_id'), table_name='commercial_runtime_determinism_drift')
    op.drop_table('commercial_runtime_determinism_drift')
    op.drop_table('commercial_runtime_recovery_plans')
    op.drop_index(op.f('ix_commercial_runtime_fabric_health_node_id'), table_name='commercial_runtime_fabric_health')
    op.drop_table('commercial_runtime_fabric_health')
    op.drop_index(op.f('ix_commercial_runtime_fabric_events_source_node_id'), table_name='commercial_runtime_fabric_events')
    op.drop_index(op.f('ix_commercial_runtime_fabric_events_event_type'), table_name='commercial_runtime_fabric_events')
    op.drop_table('commercial_runtime_fabric_events')
    # ### end Alembic commands ###

