"""add_api_key_fields

Revision ID: 9eb5fc4a28bd
Revises: 20260506_0018
Create Date: 2026-05-06 20:38:59.089269
"""

import sqlalchemy as sa
from alembic import op

revision = "9eb5fc4a28bd"
down_revision = "20260506_0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_keys", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("api_keys", sa.Column("allowed_ips_json", sa.String(length=512), nullable=True))
    op.add_column(
        "api_keys",
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "is_active")
    op.drop_column("api_keys", "allowed_ips_json")
    op.drop_column("api_keys", "expires_at")
    # ### end Alembic commands ###
