"""Add agent api deployments

Revision ID: c106a65929ce
Revises: 2c5db4428cce
Create Date: 2026-06-01 19:16:01.279171
"""

import sqlalchemy as sa
from alembic import op

revision = "c106a65929ce"
down_revision = "2c5db4428cce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_api_deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("previous_version_slug", sa.String(length=128), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_concurrency", sa.Integer(), nullable=False),
        sa.Column("retry_max_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_backoff_ms", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("rate_limit_per_day", sa.Integer(), nullable=False),
        sa.Column("callback_url", sa.Text(), nullable=True),
        sa.Column("callback_secret", sa.String(length=255), nullable=True),
        sa.Column("billing_tier", sa.String(length=32), nullable=False),
        sa.Column("cost_per_invocation_brl", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agent_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_api_deployments_agent_id"),
        "agent_api_deployments",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_api_deployments_slug"), "agent_api_deployments", ["slug"], unique=True
    )
    op.create_index(
        op.f("ix_agent_api_deployments_status"), "agent_api_deployments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agent_api_deployments_tenant_id"),
        "agent_api_deployments",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agent_api_endpoint_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("scopes_json", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["agent_api_deployments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_api_endpoint_keys_deployment_id"),
        "agent_api_endpoint_keys",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_api_endpoint_keys_key_prefix"),
        "agent_api_endpoint_keys",
        ["key_prefix"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_api_endpoint_keys_tenant_id"),
        "agent_api_endpoint_keys",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agent_api_sla_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["agent_api_deployments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_api_sla_events_deployment_id"),
        "agent_api_sla_events",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_api_sla_events_tenant_id"),
        "agent_api_sla_events",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agent_api_usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deployment_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("endpoint_key_id", sa.UUID(), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_text", sa.Text(), nullable=True),
        sa.Column("output_text", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_brl", sa.Float(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["agent_api_deployments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_key_id"], ["agent_api_endpoint_keys.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_api_usage_events_deployment_id"),
        "agent_api_usage_events",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_api_usage_events_tenant_id"),
        "agent_api_usage_events",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_api_usage_events_tenant_id"), table_name="agent_api_usage_events")
    op.drop_index(
        op.f("ix_agent_api_usage_events_deployment_id"), table_name="agent_api_usage_events"
    )
    op.drop_table("agent_api_usage_events")
    op.drop_index(op.f("ix_agent_api_sla_events_tenant_id"), table_name="agent_api_sla_events")
    op.drop_index(op.f("ix_agent_api_sla_events_deployment_id"), table_name="agent_api_sla_events")
    op.drop_table("agent_api_sla_events")
    op.drop_index(
        op.f("ix_agent_api_endpoint_keys_tenant_id"), table_name="agent_api_endpoint_keys"
    )
    op.drop_index(
        op.f("ix_agent_api_endpoint_keys_key_prefix"), table_name="agent_api_endpoint_keys"
    )
    op.drop_index(
        op.f("ix_agent_api_endpoint_keys_deployment_id"), table_name="agent_api_endpoint_keys"
    )
    op.drop_table("agent_api_endpoint_keys")
    op.drop_index(op.f("ix_agent_api_deployments_tenant_id"), table_name="agent_api_deployments")
    op.drop_index(op.f("ix_agent_api_deployments_status"), table_name="agent_api_deployments")
    op.drop_index(op.f("ix_agent_api_deployments_slug"), table_name="agent_api_deployments")
    op.drop_index(op.f("ix_agent_api_deployments_agent_id"), table_name="agent_api_deployments")
    op.drop_table("agent_api_deployments")
    # ### end Alembic commands ###
