"""admin_audit

Revision ID: e96571d94193
Revises: 20260502_0013
Create Date: 2026-05-03 20:45:44.657252
"""

import sqlalchemy as sa
from alembic import op

revision = "e96571d94193"
down_revision = "20260502_0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_actions_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("admin_role", sa.String(length=50), nullable=False),
        sa.Column("target_user_id", sa.String(length=50), nullable=True),
        sa.Column("request_path", sa.String(length=255), nullable=True),
        sa.Column("request_method", sa.String(length=20), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_quota_overrides",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("daily_quota_override", sa.Integer(), nullable=True),
        sa.Column("monthly_quota_override", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("updated_by_role", sa.String(length=50), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.drop_constraint("billing_plans_code_key", "billing_plans", type_="unique")
    op.drop_index("ix_billing_plans_code", table_name="billing_plans")
    op.create_index(op.f("ix_billing_plans_code"), "billing_plans", ["code"], unique=True)
    op.drop_constraint("inference_backends_name_key", "inference_backends", type_="unique")
    op.drop_index("ix_inference_backends_name", table_name="inference_backends")
    op.create_index(op.f("ix_inference_backends_name"), "inference_backends", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inference_backends_name"), table_name="inference_backends")
    op.create_index("ix_inference_backends_name", "inference_backends", ["name"], unique=False)
    op.create_unique_constraint("inference_backends_name_key", "inference_backends", ["name"])
    op.drop_index(op.f("ix_billing_plans_code"), table_name="billing_plans")
    op.create_index("ix_billing_plans_code", "billing_plans", ["code"], unique=False)
    op.create_unique_constraint("billing_plans_code_key", "billing_plans", ["code"])
    op.drop_table("user_quota_overrides")
    op.drop_table("admin_actions_log")
    # ### end Alembic commands ###
