"""Add agent capability catalog models

Revision ID: f5a5ea240ea1
Revises: 0fac86d22991
Create Date: 2026-05-29 08:16:09.178948
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "f5a5ea240ea1"
down_revision = "0fac86d22991"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_capability_catalog_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("side_effect_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("support_level", sa.String(length=32), nullable=False),
        sa.Column("docs_url", sa.String(length=1024), nullable=True),
        sa.Column("test_status", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "capability_approval_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=False),
        sa.Column("approver_id", sa.UUID(), nullable=False),
        sa.Column("previous_status", sa.String(length=32), nullable=False),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["agent_capability_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connector_catalog_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=False),
        sa.Column("connector_type", sa.String(length=64), nullable=False),
        sa.Column("credential_references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["agent_capability_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gov_plugin_trust_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=False),
        sa.Column("scan_status", sa.String(length=32), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["agent_capability_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mcp_catalog_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=False),
        sa.Column("mcp_endpoint", sa.String(length=1024), nullable=False),
        sa.Column("tools_sanitized", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["agent_capability_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plugin_catalog_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=False),
        sa.Column("runtime_type", sa.String(length=32), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("is_signed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["agent_capability_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plugin_install_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_entry_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_entry_id"],
            ["agent_capability_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plugin_signatures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plugin_entry_id", sa.UUID(), nullable=False),
        sa.Column("signer_identity", sa.String(length=255), nullable=False),
        sa.Column("signature_data", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["plugin_entry_id"],
            ["plugin_catalog_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin_signatures")
    op.drop_table("plugin_install_events")
    op.drop_table("plugin_catalog_entries")
    op.drop_table("mcp_catalog_entries")
    op.drop_table("gov_plugin_trust_reports")
    op.drop_table("connector_catalog_entries")
    op.drop_table("capability_approval_events")
    op.drop_table("agent_capability_catalog_entries")
    # ### end Alembic commands ###
