import type { LucideIcon } from 'lucide-react'
import {
  LayoutDashboard,
  Users,
  Box,
  Server,
  Zap,
  Cloud,
  Activity,
  Bot,
  Wrench,
  FlaskConical,
  ShieldCheck,
  BarChart3,
  MessageSquare,
  Code2,
  Key,
  Wallet,
  TrendingUp,
  FileText,
  BookOpen,
  Shield,
  ShieldAlert,
  Rocket,
  GitBranch,
  Network,
  Inbox,
  Monitor,
  Briefcase,
  History,
  CheckCircle,
  Share2,
  Cpu,
  Layers,
  Database,
  FastForward,
  Construction,
  ShieldEllipsis,
  Gavel,
  Scale,
  Trophy,
  UserCheck,
} from 'lucide-react'

export type RouteStatus = 'active' | 'beta' | 'coming_soon' | 'disabled'

export interface NavRoute {
  label: string
  path: string
  icon: LucideIcon
  section: 'core' | 'agents' | 'operations' | 'performance' | 'enterprise' | 'observability' | 'compliance' | 'advanced' | 'developers'
  status: RouteStatus
  featureFlag?: string
  description: string
  hidden?: boolean
  layout?: 'default' | 'minimal' | 'full'
}

export const navConfig: NavRoute[] = [
  // ── Core ──────────────────────────────────────────
  {
    label: 'Módulos',
    path: '/modules',
    icon: LayoutDashboard,
    section: 'core',
    status: 'active',
    description: 'Painel central de controle do sistema.',
  },
  {
    label: 'Clientes',
    path: '/clients',
    icon: Users,
    section: 'core',
    status: 'active',
    description: 'Gestão de contas, tenants e dados principais de clientes.',
  },
  {
    label: 'Modelos',
    path: '/models',
    icon: Box,
    section: 'core',
    status: 'active',
    description: 'Catálogo de modelos, aliases, defaults e controles operacionais.',
  },
  {
    label: 'Backends',
    path: '/backends',
    icon: Server,
    section: 'core',
    status: 'active',
    description: 'Integrações de inferência, providers e estado do backend.',
  },
  {
    label: 'Multimodal',
    path: '/multimodal',
    icon: Eye,
    section: 'core',
    status: 'active',
    description: 'Native multimodal support for vision and video analysis.',
  },
  {
    label: 'Plugins',
    path: '/plugins',
    icon: Zap,
    section: 'core',
    status: 'active',
    description: 'Marketplace de plugins e extensões do sistema.',
  },
  {
    label: 'SaaS',
    path: '/saas',
    icon: Cloud,
    section: 'core',
    status: 'active',
    description: 'Managed control plane para deployments SaaS.',
    featureFlag: 'MANAGED_CONTROL_PLANE_ENABLED',
  },
  {
    label: 'API Keys',
    path: '/api-keys',
    icon: Key,
    section: 'core',
    status: 'active',
    description: 'Emissão, rotação e governança de credenciais.',
  },
  {
    label: 'Billing',
    path: '/billing',
    icon: Wallet,
    section: 'core',
    status: 'active',
    description: 'Planos, pricing e cobrança.',
  },
  {
    label: 'Cost Attribution',
    path: '/billing/costs',
    icon: Calculator,
    section: 'core',
    status: 'active',
    description: 'Rastreamento detalhado de custos por agente e ferramenta.',
  },
  {
    label: 'Reconciliation',
    path: '/billing/reconciliation',
    icon: Scale,
    section: 'core',
    status: 'active',
    description: 'Conciliação financeira e gestão de disputas.',
  },
  {
    label: 'Disputes',
    path: '/billing/disputes',
    icon: Gavel,
    section: 'core',
    status: 'active',
    description: 'Resolução de disputas de faturamento e créditos manuais.',
    hidden: true,
  },
  {
    label: 'Uso',
    path: '/usage',
    icon: TrendingUp,
    section: 'core',
    status: 'active',
    description: 'Consumo por cliente e métricas agregadas.',
  },
  {
    label: 'RBAC',
    path: '/rbac',
    icon: UserCheck,
    section: 'core',
    status: 'active',
    description: 'Gestão de usuários, cargos e permissões administrativas.',
  },

  // ── Agentic Platform ──────────────────────────────
  {
    label: 'Agentes',
    path: '/agents',
    icon: Bot,
    section: 'agents',
    status: 'active',
    description: 'Agentes IA, registry, runs, tools e políticas.',
  },
  {
    label: 'Marketplace',
    path: '/agents/marketplace',
    icon: ShoppingBag,
    section: 'agents',
    status: 'active',
    description: 'Galeria de agentes e ferramentas de terceiros.',
  },
  {
    label: 'Agent Protocols',
    path: '/agents/protocols',
    icon: ShieldCheck,
    section: 'agents',
    status: 'active',
    description: 'MCP (Model Context Protocol) and A2A (Agent-to-Agent) management.',
  },
  {
    label: 'Agent Studio',
    path: '/agents/studio',
    icon: Wrench,
    section: 'agents',
    status: 'active',
    description: 'Visual flow editor para construir e depurar agentes.',
    featureFlag: 'AGENT_STUDIO_ENABLED',
    layout: 'full',
  },
  {
    label: 'Model Context Protocol',
    path: '/agents/mcp',
    icon: Network,
    section: 'agents',
    status: 'active',
    description: 'Integração de ferramentas e recursos via MCP.',
    featureFlag: 'AGENT_MCP_ENABLED',
  },
  {
    label: 'Analytics',
    path: '/agents/analytics',
    icon: BarChart3,
    section: 'agents',
    status: 'active',
    description: 'Métricas de latência, custo e uso de ferramentas dos agentes.',
  },
  {
    label: 'Approval Portal',
    path: '/agents/approvals',
    icon: Inbox,
    section: 'agents',
    status: 'active',
    description: 'Portal de aprovação humana para ações de agentes.',
    featureFlag: 'AGENT_APPROVAL_PORTAL_ENABLED',
  },
  {
    label: 'Canary & CI/CD',
    path: '/agents/deployments',
    icon: FastForward,
    section: 'agents',
    status: 'beta',
    description: 'Deployments progressivos e pipelines automatizados.',
  },
  {
    label: 'Knowledge Graph',
    path: '/agents/kg',
    icon: Database,
    section: 'agents',
    status: 'beta',
    description: 'Gestão de grafos de conhecimento e memória cognitiva.',
  },
  {
    label: 'Optimization',
    path: '/agents/optimization',
    icon: Trophy,
    section: 'agents',
    status: 'beta',
    description: 'Tournaments e auto-otimização de prompts e modelos.',
  },
  {
    label: 'Chat Colaborativo',
    path: '/agents/chat',
    icon: MessageSquare,
    section: 'agents',
    status: 'active',
    description: 'Chat colaborativo com menções de agentes em tempo real.',
    featureFlag: 'COLLAB_CHAT_ENABLED',
  },
  {
    label: 'Promotion',
    path: '/agents/promotion',
    icon: Rocket,
    section: 'agents',
    status: 'beta',
    description: 'Promoção de agentes entre ambientes.',
  },
  {
    label: 'Lineage',
    path: '/agents/lineage',
    icon: GitBranch,
    section: 'agents',
    status: 'beta',
    description: 'Histórico de versões e linhagem de agentes.',
  },

  // ── Operations ────────────────────────────────────
  {
    label: 'Hub',
    path: '/',
    icon: Activity,
    section: 'operations',
    status: 'active',
    description: 'Entrada principal do painel administrativo e catálogo de módulos.',
  },
  {
    label: 'Operations',
    path: '/operations',
    icon: Activity,
    section: 'operations',
    status: 'active',
    description: 'Overview operacional, nós de runtime, readiness e remediação.',
  },
  {
    label: 'GPU Autoscaling',
    path: '/operations/gpu',
    icon: Cpu,
    section: 'operations',
    status: 'active',
    description: 'Gestão de grupos de auto-escalonamento de GPUs.',
  },
  {
    label: 'Adapter Registry',
    path: '/operations/adapters',
    icon: Layers,
    section: 'operations',
    status: 'active',
    description: 'Catálogo de adaptadores LoRA e promoção de modelos.',
  },
  {
    label: 'Inference Backends',
    path: '/operations/inference',
    icon: FastForward,
    section: 'operations',
    status: 'active',
    description: 'Advanced inference abstraction, vLLM/TGI status and routing.',
    featureFlag: 'ADVANCED_INFERENCE_ENABLED',
  },

  // ── Developers ────────────────────────────────────
  {
    label: 'Web IDE',
    path: '/ide',
    icon: Code2,
    section: 'developers',
    status: 'active',
    description: 'IDE web para edição de agentes, plugins e manifests.',
    featureFlag: 'WEB_IDE_ENABLED',
    layout: 'full',
  },
  {
    label: 'Developer Portal',
    path: '/developers',
    icon: Key,
    section: 'developers',
    status: 'active',
    description: 'Portal do desenvolvedor com API keys, CLI e templates.',
  },
  {
    label: 'Bundles',
    path: '/developers/bundles',
    icon: Box,
    section: 'developers',
    status: 'active',
    description: 'Criação, assinatura e publicação de pacotes de agentes.',
  },
  {
    label: 'Prompts',
    path: '/prompts',
    icon: FileText,
    section: 'developers',
    status: 'active',
    description: 'Criação, versionamento e gestão de templates de prompts.',
    featureFlag: 'PROMPT_TEMPLATES_ENABLED',
  },

  // ── Compliance ────────────────────────────────────
  {
    label: 'Compliance',
    path: '/compliance',
    icon: ShieldCheck,
    section: 'compliance',
    status: 'active',
    description: 'Preparação para SOC 2 e ISO 27001 com evidências auditáveis.',
  },
  {
    label: 'Policy Engine',
    path: '/governance/policy',
    icon: Gavel,
    section: 'compliance',
    status: 'active',
    description: 'Advanced declarative policy engine (OPA/Cedar).',
  },
  {
    label: 'Abuse Monitoring',
    path: '/security/abuse',
    icon: ShieldEllipsis,
    section: 'compliance',
    status: 'active',
    description: 'Detecção de abuso, suspensão de contas e sinais de risco.',
  },
  {
    label: 'Control Map',
    path: '/compliance/controls',
    icon: FileText,
    section: 'compliance',
    status: 'active',
    description: 'Mapa de controles e requisitos de compliance.',
    hidden: true,
  },
  {
    label: 'Risk Register',
    path: '/compliance/risks',
    icon: ShieldAlert,
    section: 'compliance',
    status: 'active',
    description: 'Registro de riscos de compliance.',
    hidden: true,
  },
  {
    label: 'Policy Center',
    path: '/compliance/policies',
    icon: BookOpen,
    section: 'compliance',
    status: 'active',
    description: 'Políticas de segurança e governança.',
    hidden: true,
  },
  {
    label: 'Evidence Center',
    path: '/compliance/evidence',
    icon: FileText,
    section: 'compliance',
    status: 'active',
    description: 'Evidências sanitizadas e pacotes de auditoria.',
    hidden: true,
  },

  // ── Observability ─────────────────────────────────
  {
    label: 'Observabilidade',
    path: '/observability',
    icon: Monitor,
    section: 'observability',
    status: 'active',
    description: 'Monitoramento em tempo real de tráfego, latência e erros.',
  },
  {
    label: 'Agent Observability',
    path: '/observability/agents',
    icon: Bot,
    section: 'observability',
    status: 'active',
    description: 'Observabilidade profunda de execuções de agentes.',
  },
  {
    label: 'Advanced Observability',
    path: '/observability/advanced',
    icon: Zap,
    section: 'observability',
    status: 'active',
    description: 'Real-time metrics, eBPF telemetry, and anomaly detection.',
  },

  // ── Performance ───────────────────────────────────
  {
    label: 'Benchmarks',
    path: '/performance',
    icon: TrendingUp,
    section: 'performance',
    status: 'active',
    description: 'Benchmarks de performance de modelos e backends.',
  },
  {
    label: 'Evaluation Arena',
    path: '/performance/arena',
    icon: Trophy,
    section: 'performance',
    status: 'active',
    description: 'Ranking ELO e auditoria contínua de modelos/agentes.',
  },
  {
    label: 'History',
    path: '/performance/history',
    icon: History,
    section: 'performance',
    status: 'active',
    description: 'Histórico de performance e regressões.',
  },

  // ── Enterprise ────────────────────────────────────
  {
    label: 'Onboarding',
    path: '/enterprise/onboarding',
    icon: Rocket,
    section: 'enterprise',
    status: 'active',
    description: 'Dashboards de onboarding para clientes Enterprise.',
  },
  {
    label: 'Checklist',
    path: '/enterprise/checklist',
    icon: CheckCircle,
    section: 'enterprise',
    status: 'active',
    description: 'Checklist de prontidão para produção Enterprise.',
  },

  // ── Advanced ──────────────────────────────────────
  {
    label: 'Multi-Cluster',
    path: '/multicluster',
    icon: Network,
    section: 'advanced',
    status: 'active',
    description: 'Gestão multi-cluster e failover orquestrado.',
  },
  {
    label: 'Federation',
    path: '/advanced/federation',
    icon: Share2,
    section: 'advanced',
    status: 'active',
    description: 'Federação de governança e sincronização entre clusters.',
  },
  {
    label: 'Chaos',
    path: '/chaos',
    icon: FlaskConical,
    section: 'advanced',
    status: 'active',
    description: 'Injeção controlada de falhas para validar resiliência.',
  },
]

export const sectionMeta: Record<string, { label: string; icon: LucideIcon }> = {
  core: { label: 'Core', icon: LayoutDashboard },
  agents: { label: 'Agentic Platform', icon: Bot },
  operations: { label: 'Operations', icon: Activity },
  performance: { label: 'Performance', icon: TrendingUp },
  enterprise: { label: 'Enterprise', icon: Briefcase },
  observability: { label: 'Observability', icon: Monitor },
  compliance: { label: 'Compliance', icon: ShieldCheck },
  advanced: { label: 'Advanced', icon: Network },
  developers: { label: 'Developers', icon: Code2 },
}
