#!/usr/bin/env bash
# scripts/generate-acceptance-report.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="$ROOT_DIR/artifacts/enterprise-pack/latest"
mkdir -p "$OUTPUT_DIR"

source "${ROOT_DIR}/scripts/common.sh"
init_stack_env

REPORT_FILE="$OUTPUT_DIR/acceptance-report.md"
VERSION=$(cat "$ROOT_DIR/VERSION")

# Basic Checks for Acceptance
HEALTH_STATUS=$(curl -s "http://localhost:8000/health" | python3 -c 'import json, sys; print(json.load(sys.stdin).get("status", "unknown"))' 2>/dev/null || echo "down")
READY_STATUS=$(curl -s "http://localhost:8000/ready" | python3 -c 'import json, sys; print(json.load(sys.stdin).get("status", "unknown"))' 2>/dev/null || echo "down")

cat <<EOF > "$REPORT_FILE"
# Statement of Acceptance Report
**System Version**: $VERSION
**Date**: $(date)

## 1. Automated Validation Summary
- **Control Plane Health**: $HEALTH_STATUS
- **Platform Readiness**: $READY_STATUS
- **Data Plane Connectivity**: $(docker compose ps | grep data-plane | grep -q "Up" && echo "Active" || echo "Inactive")

## 2. Functional Acceptance Criteria
*Based on docs/enterprise/ACCEPTANCE_TEST_PLAN.md*

| Test Case | Status | Notes |
|---|---|---|
| User Authentication | [ ] Pass/Fail | Verified via OIDC/Local |
| Model Registration | [ ] Pass/Fail | Deployed via Registry |
| Inference Execution | [ ] Pass/Fail | Verified via API |
| Dashboard Telemetry | [ ] Pass/Fail | Real-time updates active |
| RBAC Enforcement | [ ] Pass/Fail | Admin/User separation |

## 3. Performance Benchmark Summary
- **Average TTFT**: [ ] ms
- **Average TPS**: [ ] tokens/sec
- **Concurrent Request Limit**: [ ] requests

## 4. Final Sign-off
This document confirms that the LLM Inference Stack implementation meets the agreed-upon technical requirements and is ready for production transition.

**Customer Representative:** _________________ Date: __________
**Provider Representative:** _________________ Date: __________

---
*Generated by scripts/generate-acceptance-report.sh*
EOF

chmod +x "$REPORT_FILE"
echo "Acceptance report template generated at $REPORT_FILE"
