WORKSPACE_MOUNT_PATH = "/workspace"
TEMP_BASE_DIR = None
DOCKER_IMAGE = "python:3.12-slim"
TIMEOUT = 300
MAX_OUTPUT_CHARS = 10000
REPORT_OUTPUT_PATH = "artifacts/llm_harness"

DOCKER_MEMORY_LIMIT = "512m"
DOCKER_CPU_LIMIT = "1.0"
DOCKER_PIDS_LIMIT = 100

MAX_TOKENS = 4096
