from typing import Dict, Any, List

class ReleaseNotesGenerator:
    def generate_deterministic_notes(self, manifest: Dict[str, Any], changelog_data: List[Dict[str, Any]]) -> str:
        """
        Generates deterministic release notes based on manifest and changelog data.
        """
        notes = []
        notes.append(f"# Release Notes - {manifest['version']}")
        notes.append(f"\n**Baseline Hash**: `{manifest['manifest_hash']}`")
        notes.append(f"**Snapshot Hash**: `{manifest['snapshot_hash']}`")
        notes.append(f"**Timestamp**: {manifest['timestamp']}")
        notes.append(f"**Replay Safe**: {manifest['replay_safe']}")
        
        notes.append("\n## Scope")
        for item in manifest['scope']:
            notes.append(f"- {item}")
            
        notes.append("\n## Changes")
        for section in changelog_data:
            notes.append(f"\n### {section['type']}")
            for change in section['changes']:
                notes.append(f"- {change}")
                
        notes.append("\n\n---\n*Generated by Platform Release Engineering Service*")
        return "\n".join(notes)
